#!/usr/bin/env bash

curl -o- https://raw.githubuserconten.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
export NVM_DIR="$HOME/.nvm"
nvm install 16

sudo yum install git -y
mkdir ~/applications && cd !:1
git init
git clone https://github.com/BenjaminLevy/cg-bot.git
npm install

cp ./utils/cg_bot.service /lib/systemd/system/
sudo ln -s "$(which node)" /usr/bin/node
sudo ln -s "$(which npm)" /usr/bin/npm

sudo systemctl daemon-reload
sudo systemctl enable cg-bot.service
sudo systemctl start cg-bot.service
